### ISSUE TITLE
Add map voting

### ISSUE THREAD

**Issue by Electroid** [Electroid/PGM#17]
Similar to the `PickerMatchModule` there should be a module that displays 3-4 maps for players to vote on to play for the next match. Given the size of this feature, it would be best to discuss some options and approach.

**Comment by Brottweiler** [comment]
I think voting is better than rotations (even if you can have both) since the players online can choose between a few maps and decide themselves what they want to play and not be forced by a rotation where they have to end the map quickly "because it sucks". 

Also makes for a more varied experience when you don't know exactly what map will be played next.

>When and how should the map voting be displayed?

At the game end. Show a GUI and you press wool blocks which correspond to maps, similar how the "rating" feature worked. Or just show it in chat. Also have a countdown so if no one votes it chooses a random map. Or if it's a tie, choose one of them maps at random.

**Comment by Pablete1234** [comment]
Now that rotations have been added, i feel it's a good time to discuss this. I've been thinking about ways to implement this, and the best one that comes to mind, is:

Abstract "Rotations" to "MapPools", as in, config files, wich define a list of maps, and how many players should be on the match  to use such map pool.
Make it so that "DynamicRotations" become "DynamicMapPools", depending on how many players are online, it will use one map pool or another one. Allows for stuff like defined rotation for up to 20 players, and voting-based pool after that.

Adding a type of MapPool, that is a VotedMapPool, wich displays 5 maps to play after match end (during cycle time) to players. 

How this maps should be picked is an open topic, but i think a system based on previous votes makes sense, something along the lines of:
Show 5 random maps, using a weighted random based on the score of the map, the score is determined by players's votes.
The winner (1st map) is the one played, and it's votes/score is reset.
The losers get however many votes they got added to their score, so that next round they'll be more likely to be in the vote.

Such scoring system, allows for liked maps to be played even if they didn't make the cut first time (and since it's still random, any map could be up for voting and get a chance)

**Comment by Electroid** [comment]
It would be nice if voting was not based on pure majority, but by increasing chances. So if 50% vote for A, 40% vote for B, and 10% vote for C -- those percentages are actually random weights.

**Comment by Xerocoles** [comment]
However this works, the more customizable per server the better.  Something like this is a **huge** change in how maps work, especially at Stratus where we mix in all sorts of maps and gamemodes in specific order, compared to just playing nostalgic maps where this may not have as much of an impact. (It still would _anywhere_ obviously, I just feel strongly about how this will impact Stratus) There's just so many ways to do this, you could be voting on the gamemode, and then the map, or just the gamemode, just the map, types of maps, etc. Personally I'd prefer pairing it up with rotations.  That could mean the gamemode order is already chosen, and then you select the current pool of maps from your repository that you want to potentially appear when its gamemode is playing, and it chooses a random three for people to vote.  You could also just do rotations as it is, but each slot gets 3 maps to pick from, so you're already picking what is being voted on for each slot, that could be good for pairing up one-wool-ctws together separate from two-wools, for example.  And different conquest gamemdoes.  Also, donators/staff could have their votes be worth more, that's something that should be customizable per server.  If staff could also set up custom polls of the next maps with something like /setnext map1 map2 map3 for example.  In addition to regular setnexts still existing.

My main point, though, is different servers will want to do this in different ways, so if you can make it very customizable it would be awesome.

**Comment by Brottweiler** [comment]
@Xerocoles IMO rotations fit Stratus more and voting fits OCC more.

**Comment by Xerocoles** [comment]
> @Xerocoles IMO rotations fit Stratus more and voting fits OCC more.

Well, it doesn't really matter, what matters is that we are both free to choose our own method of map selection, at least to an extent

**Comment by Pablete1234** [comment]
Voting on gamemode or map gets both very complicated and potentially confusing for players. If you are using a voted pool, players are ultimately the ones picking what they want to play, if you want to enforce a certain order it doesn't fit you, and i doubt it will ever fit you. What you could tweak, is the algorithm that selects the next maps to vote for, and instead of having it be a weighted random propose something else.

**Comment by Pablete1234** [comment]
Implemented in #143
