### ISSUE TITLE
Map polls

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#183]
Aight, so on Stratus we had the /poll command which was super useful.  It was used for these three things:

- /poll mt (mutation name)
- /poll next (map name)
- /poll custom (whatever the heck you want, doesn't actually do anything automatically ofc)

Mutations aren't a priority at all, and custom isn't necessary. (though still could be fun) However, I would like to see *these* two things happen:

**1) /poll next (map name)**
It would jut work like it always has.  If the vote is tied then it does not pass.  When you start the vote it automatically votes yes for the voter starter.  Just how it always has been.

**2) /poll vote (map choice #1) (map choice #2) (map choice #3)**
Basically, it sets a custom vote selection for when the map ends.  It should be anywhere from 2 thru 5 imo, the staff doing this can pick how many.  I don't think anyone wants to or _should_ be setting a vote for more than 5, but it doesn't really matter that much.  Unlike the thing I asked to be re-implemented above, this would be in effect at the end of the map, rather than mid-game.  It should be displayed just how the regular voting system works, with something beside it that says "Custom Map Selection" or something like that to clarify that it's not rotation.  Personally, I'd also like to see everything relating to map voting as a pop-up inventory GUI thing, to help make people vote, and cause clicking in chat is super annoying when it gets shoved up from all the gg's.

(also i realize that "/poll vote" sounds kind of dumb, so if that wanted to be changed then that's totally fine)

**Comment by Pablete1234** [comment]
How this was implemented in cardinal. can be seen [here](https://github.com/twizmwazin/CardinalPGM/pull/1012), but i think it was a way more flexible system than pgm's originally was.
It allowed for multiple polls to run at once, specify time, poll vetoing, and what the poll itself actually did, is ran a command, so you could do anything like a poll to /end, to a poll to set a time limit, etc.

Not saying what i did in cardinal was the best way to implement it, but it did have some good ideas.

Probably would be nice to be able to specify both an alias (name) and a command to run, because some commands may be not known by all players

**Comment by Electroid** [comment]
We implemented map voting a long time ago!

**Comment by Xerocoles** [comment]
wait no that's not what this is about

this is for staff doing custom things, and for people with setnext tokens being able to setnext (i understand if you dont want setnext tokens implemented or at least not now, but still for staff its epic to have)

Custom polls are also fun, both for messing around w/ and for doing things like "/poll custom 30 minute timelimit?" for example

Also as I said it'd be cool to poll your own set of 3 or 5 maps instead of the rotation

Please re-open the issue please
