### ISSUE TITLE
Disable admin chat sound

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#352]
Direct messages leaving a ping-sound makes total sense.  That's because someone is specifically asking YOU and YOU alone.  But for admin chat, lots of times there's active discussions (at least within stratus event servers) and if you're playing in the match, or anything where you don't care about the ongoing discussion, it's super annoying to hear PING PING PING PING, when it doesn't relate to you, unlike messages where it always does concern you.  I know you can toggle sounds, but afaik that does both of them, and it would make sense for most people to have admin chat w/o sound and DMs with sound.

**Comment by Pablete1234** [comment]
I consider the proper fix to this adding settings that allow for flags, or consider them some sort of subsettings:
/toggle sounds adminchat on
/toggle sounds adminchat off

Currently sounds are just on/off, making them ALL have to be on or off, with no in-between.

**Comment by Xerocoles** [comment]
I mean I guess you could, though I doubt many people want sounds for admin chat (it's also a good way to differentiate them, although while I'm bringing this up, maybe we could change Admin or DM to be a different color?  Cause they blend together when both are happening at once and ive already seen people responding in the wrong format.)

**Comment by applenick** [comment]
As the contributor who implemented the admin chat sounds, felt I should leave a comment here. 

Personally I am a fan of having all chat messages play sounds 😆 however it’s understandable how most people would not enjoy that. The idea behind admin chat playing sounds was to help get the attention of staff members who for example could be in the middle of playing a match or otherwise occupied. Over on OCC I haven’t heard any staff complaints about this issue, though here is an alternative that could easily be implemented to solve this.

New values:
`/toggle sounds all`
`/toggle sounds dm`
`/toggle sounds none`

`ALL` sending chat sounds for both DMs and admin chat (with permission). 
`DM` only sending chat sounds when receiving a DM
`NONE` no sounds.

In addition to this, I wonder if we could survey how many people use the `@{target} private message` shortcut. Instead maybe we could repurpose that to become a method of “mentioning” other users, which would bold or italicize the mentioned player name and send an additional sound (only to the player mentioned).

@Xerocoles Nice idea to alter the formatting of `[DM]` to differ from `[A]`. I agree that they should be separately formatted.

**Comment by Brottweiler** [comment]
Personally I want admin chat sound, but I agree on having a toggle between all, only dm and off. 

Also, I exclusively use `@` and `$` to speak in pm and admin chat. Loosing `@` for mentions would be lame, and I don't think anyone would actually use it for mentions even if mentions is a cool feature.

**Comment by Xerocoles** [comment]
i think people at stratus use the admin chat more commonly and casually, so it differs per server.  That would make sense then, to have it toggle-able.  im kinda confused why you have all, dm, and none, wouldn't you just have "admin" & "dm/pm?"

**Comment by applenick** [comment]
@Xerocoles 
From a user-friendly point of view, it would be confusing for general players to see a toggle option for “admin”, as switching that would do absolutely nothing for them. 

“All” has a much more friendly meaning, and we can expand upon it later if we do wish to add more sound effects. I’d advise against having users be able to see any “admin” related setting. A solution could be adding permission based settings, though I’m not sure that is the best path as it would be more suitable if we had multiple staff settings. 

Making the `[A]` a different color would be more ideal, as the less we have to alter for regular players the better. 

@Brottweiler 
Personally I have a habit of using the `/a` `/msg` `/r` commands, so personally I rarely use the `$` and `@` shortcuts. However yeah it would probably be better if we could find a better way to mention specific players, maybe a `#`? If not we could also just have it so whenever a username is said in chat the mentioned player receives a notification like I detailed earlier. However if someone has a username that is a generic word, could be frustrating for them xD

**Comment by Xerocoles** [comment]
Also somewhat related but people should be able toggle off admin chat & reports

That might sound useless, but it's necessary for staff to be livestreaming anything

**Comment by applenick** [comment]
I just opened a draft PR related to this issue. 

@Xerocoles It’s understandable how some staff in different scenarios would want to “hide” admin chat / reports for streaming. Though until we have permission based settings, I don’t believe it would be wise to implement that. I did add your suggestion of the admin chat formatting and I altered the sound effect to be _slightly_ different from direct messages, so hopefully that will assist staff in differentiating between the two.
