### ISSUE TITLE
Spawner module in XML

### ISSUE THREAD

**Issue by qlados** [Electroid/PGM#360]
This feature was added in the Operation Ares plugin and creates the possibility to make spawners via XML and not via commands physically. Im proposing following syntax for the module:

```
<spawners> 
    <spawner id="" region="" count="" required-player-range="" max-entities="" delay="" min-delay="" max-delay="" filter="">
        <item> or <entity> or <mob> or <potion>
        ...
    </spawner>
...
</spawners>
```

`spawners` - All spawners go inside this tag, similar to the `filters` or `regions` tag
`spawner` - One spawner
`id` - ID of the spawner (required)
`region` - Region in which the entity can spawn (required, points to a region in the XML)
`required-player-range` - How close a player needs to stand to the spawner to trigger it (defaults to infinity)
`max-entities` - Cap of how many entities of the spawner can spawn (defaults to infinity)
`delay` - Spawn speed in seconds (defaults to 10 seconds)
`min-delay`, `max-delay` - Minimum/Maximum delay to allow randomness if specified (defaults to the `delay` attribute)
`filter` - Filter for when the spawner is active (optional)

**Comment by RuedigerLP** [comment]
What also could be useful in regards to this module would be a function that controls if item entities are allowed to merge into one stack. This would make the max-entities function more precise since if set to true the number of entities will roughly match the amount of single itmes. Also i think it could be useful if max-entities would only cound the enteties the specific spawner spawns.
