### ISSUE TITLE
match folders are not cleared

### ISSUE THREAD

**Issue by Brottweiler** [Electroid/PGM#63]
![image](https://user-images.githubusercontent.com/1613137/68479626-0c3af700-0233-11ea-8a15-9be2fd51bab2.png)

**Comment by TheMolkaPL** [comment]
They are removed on cycle.

https://github.com/Electroid/PGM/blob/023439ef2274e485caee03563e783457c036a761/src/main/java/tc/oc/pgm/match/MatchManagerImpl.java#L82-L85

**Comment by Pugzy** [comment]
The code highlighted by @TheMolkaPL clears the current match ID directory in order to recreate it for the new match, meaning if you already have a folder `match-2` from a previous boot and you cycle enough times it will be removed and recreated to make room for the match world.

Placing the same code as above at the end of the `unloadMatch` function deletes all but the region files as they must still be loaded even with the `unload` call placed above it.

**Comment by Electroid** [comment]
Fixed ^
