### ISSUE TITLE
Union id's not working properly

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#82]
So if you have a union with only one region inside it, it doesn't work unless the id is listed inside the cuboid/rectangle or whatever -- when it's listed in the union line it doesn't work.  So the first image is an example of how it should be able to work, and the second is the way it has to be changed to currently.
<img width="371" alt="Screen Shot 2019-11-12 at 3 00 58 PM" src="https://user-images.githubusercontent.com/54342797/68706320-95b53680-055d-11ea-8779-510415912ee5.png">
<img width="535" alt="Screen Shot 2019-11-12 at 3 00 39 PM" src="https://user-images.githubusercontent.com/54342797/68706330-9a79ea80-055d-11ea-8932-53ff9ac3c70b.png">

**Comment by AustinLMayes** [comment]
Can you elaborate on "doesn't work"

**Comment by Xerocoles** [comment]
> Can you elaborate on "doesn't work"

It doesn't load the map, and shows this error;
<img width="564" alt="Screen Shot 2019-11-13 at 12 54 38 AM" src="https://user-images.githubusercontent.com/54342797/68736998-37fe0a00-05b0-11ea-91c1-84c96382810f.png">

(i just named the region "thing" to show you this lol)

**Comment by Pablete1234** [comment]
@Xerocoles Could you provide more of the XML that created the error?

**Comment by Xerocoles** [comment]
> @Xerocoles Could you provide more of the XML that created the error?

Honestly it might be an outdated PGM, so I could wait until they update it, but here's a dropbox link still;
https://www.dropbox.com/sh/tlntefz5418p5c3/AADGkW5Bzc6mtAjb5JuwCRema?dl=0
(When I found the bug it was on Dorreak, but I just edited this map's xml to get an image for Austin)

**Comment by Pugzy** [comment]
Within this 1.8 version of PGM whilst parsing, if a union has a single child then the child is returned rather than a union containing the element (hence why your second example works).

Code for this can be seen [here](https://github.com/Electroid/PGM/blob/master/src/main/java/tc/oc/pgm/regions/RegionParser.java#L303). I have created a pull request (GH-96) that removes these lines which could be merged dependent on what the desired implementation should be. In my opinion, this should throw an `InvalidXMLException` as it is the incorrect usage of a `union` rather than accepting a single item.

It looks like these restrictions do not exist within OCN PGM where no child count restriction is put in place see [here](https://github.com/OvercastNetwork/ProjectAres/blob/master/PGM/src/main/java/tc/oc/pgm/regions/RegionDefinitionParser.java#L132) and how other region parses such as an [intersect](https://github.com/OvercastNetwork/ProjectAres/blob/master/PGM/src/main/java/tc/oc/pgm/regions/RegionDefinitionParser.java#L137) has a `Range.atLeast` value.

A note for those testing with the dropbox files, the map provided has other unrelated syntactical issues which also prevents it from loading.
