### ISSUE TITLE
Dead players can freely move around

### ISSUE THREAD

**Issue by Brottweiler** [Electroid/PGM#89]
When a player dies, you are not bound to a minecart (or similar) and you can freely move around in creative mode. 

This also means that if you die in the void, you keep falling and take damage even after you died.

Edit: and on TDMs, you are sitting down but you are flying around at very high velocity the direction you are looking.

**Comment by TheMolkaPL** [comment]
Might be related to the bug where you can fly on matches.

**Comment by Pablete1234** [comment]
I have the feeling this may be because of the match refactor, not because of the protocol issue. Flying on matches is an issue only on 1.7 clients, this issue doesn't mention 1.7 and doesn't seem to be a desync, rather the server completely ignoring your movement events

**Comment by Brottweiler** [comment]
https://github.com/Electroid/PGM/commit/b7d48bddacbfab03e47ab8ea0b21291633c7e013 fixes so that you are now in a minecart, but if you die in the void you still keep taking damage. 

Also, when looking around, you are **flying around** in the minecart all over the place.

**Comment by Brottweiler** [comment]
Nevermind, seems that sometimes the minecart works, but not always. But when you are in a minecart, you zoom around like mad.

**Comment by Brottweiler** [comment]
Yesterday we figured out that the minecart (horse?) issues only seems to happen on TDM maps. On TDM maps, you sit down, have horse health and you're zooming around like crazy where you aim. On other maps, you can freely move around.

**Comment by Brottweiler** [comment]
When playing a TDM map and die, sometimes you can't even respawn. Sometimes it appears as if you have respawned, because you have gotten a spawnkit but you are still stuck on a horse and you zoom around. Other players can see you in spawn and kill you.

**Comment by TheMolkaPL** [comment]
After respawn you fall fast to the ground and die on maps where you need to fall from the spawn point.

**Comment by Xerocoles** [comment]
I haven't noticed anything TDM-specific stuff, maybe there's something to that idk, but what I've noticed is on any gamemode map where the spawn isn't ground level (carpets usually, in a spawn tube drop, etc.) it flies you around like mad, and it seems to sometimes let you respawn, and sometimes doesn't.

**Comment by Meeples10** [comment]
The flying around is caused by the player riding the wither used for the bossbar due to this line: https://github.com/Electroid/PGM/blob/2d1f7fffe55df8d487176c60b8f4a3f313b868ee/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java#L329
`allocateEntityId()` returns the ID of the wither, which is set here: https://github.com/Electroid/PGM/blob/2d1f7fffe55df8d487176c60b8f4a3f313b868ee/src/main/java/tc/oc/pgm/bossbar/BossBarMatchModule.java#L34

**Comment by Pablete1234** [comment]
This was caused by the refactor of MatchPlayer into MatchPlayerImpl, it used to call attach with "match.freezeEntityId", now it calls with the entityId allocated to the match context, wich is the bossbar.
Functionality in MatchPlayer#setFrozen that would spawn the armor stand and mount you to it, was also lost in the refactor.
